static char *fragSource =
"\n#version 430\n"
"#define debugmov 0\n"
"#define doAA 0\n"
"layout (location=0) uniform vec4 fpar[2];"
"\n#define iTime fpar[0].z/1000.\n"
"#define MAT_GROUND 0\n"
"#define MAT_BLU 1\n"
"int i;"
"vec3 gHitPosition = vec3(0);"
"float PI = acos(-1.);"
"float diag = sqrt(2.);"
"mat2 rot2(float a){float s=sin(a),c=cos(a);return mat2(c,s,-s,c);}"
"vec2 m(vec2 b, vec2 a){return a.x<b.x?a:b;}"
"vec2 blu(vec3 p)"
"{"
"p.x += iTime;"
"p.xy = mod(p.xy, 2.) - 1.;"
"p.xy *= rot2(iTime);"
"return vec2(length(max(abs(p)-vec3(.5),0.)), MAT_BLU);"
"}"
"vec2 map(vec3 p)"
"{"
"p.yz *= rot2(-atan(1./sqrt(2.)));"
"p.xz *= rot2(PI/4.);"
"vec2 r = blu(p);"
"return r;"
"}"
"vec3 norm(vec3 p, float dist_to_p)"
"{"
"vec2 e=vec2(1.,-1.)*.0035;"
"return normalize(e.xyy*map(p+e.xyy).x+e.yyx*map(p+e.yyx).x+e.yxy*map(p+e.yxy).x+e.xxx*map(p+e.xxx).x);"
"}"
"vec4 march(vec3 ro, vec3 rd)"
"{"
"float b,dist;"
"vec4 r = vec4(0);"
"for (i = 0; i < 100; i++){"
"gHitPosition = ro + rd * r.z;"
"vec2 m = map(gHitPosition);"
"dist = m.x;"
"if (dist < .0001) {"
"r.x = float(i)/float(200); "
"r.y = dist;"
"r.w = m.y;"
"break;"
"}"
"r.z += dist;"
"}"
"return r;"
"}"
"vec3 getmat(vec4 r)"
"{"
"vec3 p = gHitPosition.xyz;"
"switch (int(r.w)) {"
"case MAT_BLU:"
"return vec3(.2,.2,.8);"
"}"
"return vec3(1.);"
"}"
"vec3 colorHit(vec4 result, vec3 rd, vec3 normal, vec3 mat)"
"{"
"vec3 lig = normalize(vec3(.3,.3,-1.));"
"return mat * 4. * clamp(dot(normal, lig), .0, 1.);"
"/*"
"vec3 lig = normalize(vec3(0.,0.,1.));"
"return mat * (4. + clamp(dot(normal, lig), 0., 1.) * .5);"
"*/"
"}"
"out vec4 c;"
"in vec2 v;"
"void main()"
"{"
"vec2 normuv = (v + 1.) / 2;"
"vec3 ro = vec3(0.,0.,-12.), at = vec3(12.,12.,0.), rd;"
"/*"
"vec3	cf = normalize(at-ro),"
"cl = normalize(cross(cf,vec3(0,0,-1)));"
"mat3 rdbase = mat3(cl,normalize(cross(cl,cf)),cf);"
"*/"
"vec3 resultcol = vec3(0.);"
"\n#if doAA == 1\n"
"for (int aaa = 0; aaa < 2; aaa++) {"
"for (int aab = 0; aab < 2; aab++) {"
"\n#else\n"
"int aaa = 0, aab = 0;"
"\n#endif\n"
"vec2 iResolution = fpar[0].xy;"
"vec2 uv = v*(iResolution + vec2(float(aaa),float(aab))/4)/iResolution;"
"uv.y /= iResolution.x/iResolution.y;"
"vec3 col = vec3(.8);"
"ro = vec3(uv*5.,-90.), rd=vec3(0.,0.,1.);"
"vec4 result = march(ro, rd);"
"if (result.x > 0.) { "
"vec3 normal = norm(gHitPosition, result.y);"
"col = colorHit(result, rd, normal, getmat(result)*.3);"
"}"
"resultcol += col;"
"\n#if doAA == 1\n"
"}"
"}"
"resultcol /= 4.;"
"\n#endif\n"
"c = vec4(pow(resultcol, vec3(.4545)), 1.0); "
"}"
;